### ISSUE TITLE
Link about Yubico Authenticator goes nowhere

### ISSUE THREAD

**Issue by riastradh-brave** [brave/otpauth-recovery#1]
On [line 34](https://github.com/brave/otpauth-recovery/blame/336ed8c6899f4be038ddfd6b2b61b525e112ecce/README.md#L34) README.md points to

https://www.yubico.com/support/knowledge-base/categories/articles/yubico-authenticator-download/

but this just redirects to https://www.yubico.com/.

**Comment by mrose17** [comment]
thanks! fixed!
